# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SUWIKI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'  
  pod 'Elliotable'
  pod 'Then'
  pod 'SnapKit'
  pod 'Reusable'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'
  pod 'FirebaseDatabase'
  # Pods for SUWIKI 

  post_install do |installer|
      installer.pods_project.targets.each do |target|
  	  target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
  
  target 'TimetableWidgetExtension' do
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Analytics'
    pod 'FirebaseDatabase'
  end
end
