# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uswTimeTable1.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Elliotable'
  pod 'RealmSwift'
  pod 'Realm'
  pod 'DropDown'
  pod 'Gifu'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  # Pods for uswTimeTable1.0


end
